### ISSUE TITLE
ngc aot build fail

### ISSUE THREAD

**Issue by tobiasmuecksch** [MikaAK/angular-safeguard#24]
When I'm trying to transpile my ionic 2 app which uses ngc, I encounter this error:
`Error: Unexpected value 'LockerModule' imported by the module 'AppModule'`

This is the problematic code:
```
// Some angular and ionic related imports above...
import {LockerModule, Locker, LockerConfig} from 'angular2-locker';
let components = [MyPage];

@NgModule({
	declarations: components,
	imports: [
		IonicModule.forRoot(MyApp, {
			mode: 'ios'
		}),
		LockerModule
	],
	bootstrap: [IonicApp],
	entryComponents: components,
	providers: [Settings, {provide: ErrorHandler, useClass: IonicErrorHandler}]
})

export class AppModule {
	constructor (protected locker: Locker){}
}
```

How can I fix this issue? I can't find any helpful information by googling.

**Comment by tobiasmuecksch** [comment]
Here is a similar issue with another angular 2 module.

https://github.com/oferh/ng2-completer/issues/44

It looks like this is an issue with angular2-locker, not supporting ngc.

**Comment by tobiasmuecksch** [comment]
Potential fix in this stack overflow answer
:
http://stackoverflow.com/questions/39867324/unexpected-value-x-imported-by-the-module-z-when-using-flag-aot

**Comment by MikaAK** [comment]
Will release with next version thanks for all the info

**Comment by MikaAK** [comment]
This is proving to be more difficult than expected. I may have to release this with an update since it's not working when I try adding in AoTPlugin

**Comment by tobiasmuecksch** [comment]
Okay. No hurry.

**Comment by MikaAK** [comment]
Doing AoT requires a bit of a change. The new api can either be 

`locker.put(DRIVERS.SESSION, 'key', value)`
or a different injectable for each type
`sessionLocker.put('key', value)`

I'm inclined to use the former as it allows for more dynamic code and is easier to test. What are your opinions @tobiasmuecksch , @VuongN?

**Comment by VuongN** [comment]
At first impression, I like `sessionLocker.put('key', value)` for the neat syntax and decoupling because each driver can do different things so you'd end up with a less complicated `locker.put`. I hear you about the testing bit though.

**Comment by tobiasmuecksch** [comment]
@MikaAK Well. In my opinion both approaches aren't very convenient. If I had to choose one, I'd take the first option.

But how about having some kind of wrapper?

Like: 
```
let myLocker = locker.getLocker(DRIVERS.SESSION);
locker.put('key', value);
``` 
The getLocker method (the name isn't optimal, but I didn't come up with a better one) creates a wrapper which does `locker.put(DRIVERS.SESSION, 'key', value)` when calling the `put()` method.

**Comment by tobiasmuecksch** [comment]
@VuongN As far as I understand @MikaAK he has to circumvent some issues with ngc aot compilation. That means the standard way of providing the `locker.put('key', value)`-method is not an option.

**Comment by MikaAK** [comment]
Unfortunately there is no way to return a new instance of itself because that breaks AoT so a getLocker method would end with the locker being just a wrapper to get storages which then begs the question why not just use way 1 with a separate type for each.  I'm still leaning towards way two however as it will mean less on the user side to handle non supported drivers especially since in the case of safari private session and localstorage are unavailable so it would error unless you started doing checks and falling back to memory driver each time. I've already finished implementing way 2 as it was the easiest to switch to so I will probably release that and then see if there's to much complaint. Alternatively way 2 also allows for more expansion as users can create your own driver types

**Comment by dmitriirudakov** [comment]
@MikaAK I'm using yours plugin version 1.0.0
I have angular-cli application ("angular-cli": "1.0.0-beta.26", "@angular/core": "^2.4.5") and when I try to compile app with `ng serve` I see an error below:

`ERROR in Error encountered resolving symbol values statically. Calling function 'LockerModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in ./src/app/app.module.ts, resolving symbol AppModule ./src/app/app.module.ts`

Looks that it happens because plugin doesn't support AoT compilation and doesn't create metadata.json file.

Could you fix it, please?

**Comment by dmitriirudakov** [comment]
@MikaAK I'm using yours plugin version 1.0.0
I have angular-cli application ("angular-cli": "1.0.0-beta.26", "@angular/core": "^2.4.5") and when I try to compile app with `ng serve` I see an error below:

`ERROR in Error encountered resolving symbol values statically. Calling function 'LockerModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in ./src/app/app.module.ts, resolving symbol AppModule ./src/app/app.module.ts`

Looks that it happens because plugin doesn't support AoT compilation and doesn't create metadata.json file.

Could you fix it, please?

**Comment by tobiasmuecksch** [comment]
@MikaAK Roger. I think this information should then be mentioned with a little statement why in the readme in order to prevent confusion.

**Comment by MikaAK** [comment]
Progress update, just working on getting tests to pass, I've already got the build to complete with AoT

**Comment by Saratov** [comment]
Hi! Could you release fixed version on this week?

**Comment by rsnj** [comment]
Any updates on this issue? We are looking for a way to handle local storage in Angular and came across your project. Unfortunately, our project is using AOT and haven't been able to integrate your library.

**Comment by MikaAK** [comment]
I do have the work done but unfortunately the tests need to change to accommodate the new style. I can push up the code to master once I'm home so you can begin to use it.  Unfortunately I've been very busy with work and another side project that I've had no time to fix the tests.  But I'll give it a stab over the weekend if I finish my other tasks.

**Comment by onerandomgig** [comment]
Hi @MikaAK, Thanks for this awesome library. Were you able to push your AoT changes. I made some local changes to get this working with AoT but when i run in Safari Private Mode, I get this weird error - EXCEPTION: Can't find variable: __DEV__ .... Any thoughts on this?

**Comment by MikaAK** [comment]
@onerandomgig it is pushed! The error is due to not being built and having compiler variables in the code

**Comment by achanthamynavong** [comment]
Any update on the fix?
